source 'https://github.com/CocoaPods/Specs.git'
#source 'git@gitlab.com:cnstar/ZCMRepos.git'

platform :ios, '8.0'
inhibit_all_warnings!
#use_frameworks!

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
